services:

  ssl-vision-client:
    image: robocupssl/ssl-vision-client:latest
    network_mode: "host"
    restart: "no"
    container_name: ssl-viewer
    #depends_on:
      #- sim

  ssl-game-controller:
    image: robocupssl/ssl-game-controller:latest
    network_mode: "host"
    container_name: game-controller
    #depends_on:
      #- sim
    restart: "no"
    volumes:
      - ./config/:/config
      - ./data/:/data

        #sim:
        #  image: roboticserlangen/simulatorcli:commit-6a4e1c06533b
        #  environment:
        #    GEOMETRY: "2020B"
        #    REALISM: "RC2021"
        #  networks:
        #    - simulation
        #  restart: "no"
        #  container_name: vision

  controller:
    image: ghcr.io/liu-seegoals/controller:latest
    tty: true
    network_mode: "host"
    container_name: ai
    restart: "no"
    volumes:
      - ./.env:/var/controller/.env

  game-viewer:
    image: ghcr.io/liu-seegoals/game-viewer:latest
    tty: true
    network_mode: "host"
    depends_on:
      - controller
    container_name: viewer
    restart: "no"
    volumes:
      - ./.env:/.env
