services:
  ssl-vision-client:
    image: robocupssl/ssl-vision-client:latest
    command:
      - "-visionAddress"
      - "${SSL_VISION_MULTICAST_ADDR}:${SSL_SIM_VISION_MAIN_PORT}"
      - "-visualizationAddress"
      - "${SSL_VISION_MULTICAST_ADDR}:${SSL_VISION_VIZ_PORT}"
      - "-address"
      - ":${WEB_VISION_UI_PORT}"
    network_mode: "host"
    restart: "no"
    container_name: ssl-viewer

  controller:
    build: ./controller
    image: ""
    tty: true
    network_mode: "host"
    container_name: ai
    volumes:
      - ./controller/:/var/controller
      - ./.env:/.env # If this was /var/controller/.env then the .env file will be volumed into the workspace of GameViewer
    command: tail -f /dev/null

  ssl-game-controller:
    profiles:
      - donotstart

  sim:
    profiles:
      - donotstart

  vision:
    profiles:
      - donotstart

  game-viewer:
    profiles:
      - donotstart
