# docker-compose.local-gameviewer.yml (GHCR controller, local game viewer)
services:
  game-viewer:
    build: ./GameViewer
    image: ""
    tty: true
    ports:
      - "5173:5173"
    networks:
      - simulation
    container_name: viewer
    depends_on:
      - controller
    volumes:
      - ./GameViewer/:/var/GameViewer
      - ./.env:/.env
    command: tail -f /dev/null
