version: '3.5'

services:

  # ssl-vision-client:
  #   image: robocupssl/ssl-vision-client:latest
  #   command:
  #     - "-visionAddress"
  #     - "${SSL_VISION_MULTICAST_ADDR}:${SSL_VISION_MAIN_PORT}"
  #     - "-visualizationAddress"
  #     - "${SSL_VISION_MULTICAST_ADDR}:${SSL_VISION_VIZ_PORT}"
  #     - "-address"
  #     - ":${WEB_VISION_UI_PORT}"
  #   ports:
  #     - "${WEB_VISION_UI_PORT}:${WEB_VISION_UI_PORT}"
  #   networks:
  #     - simulation
  #   depends_on:
  #     - sim

  sim:
    image: roboticserlangen/simulatorcli:commit-6a4e1c06533b
    environment:
      GEOMETRY: "2020B"
      REALISM: "RC2021"
    networks:
      - simulation

  controller:
    image: ghcr.io/liu-seegoals/controller:latest
    env_file:
      - .env
    tty: true
    ports:
      - "8080:8080"
    networks:
      - simulation
    volumes:
      - ./.env:/var/controller/.env

  game-viewer:
    image: ghcr.io/liu-seegoals/game-viewer:latest
    tty: true
    ports:
      - "5173:5173"
    networks:
      - simulation
    depends_on:
      - controller
    volumes:
      - ./.env:/.env

networks:
  simulation: