services:

  vision:
    image: ghcr.io/liu-seegoals/ssl-vision:latest
    environment:
      - QT_QPA_PLATFORM=offscreen
    stdin_open: true
    tty: true
    networks:
      - simulation

  ssl-viewer:
    image: robocupssl/ssl-vision-client:latest
    command:
      - "-visionAddress"
      - "${SSL_VISION_MULTICAST_ADDR}:${SSL_REAL_VISION_MAIN_PORT}"
      - "-visualizationAddress"
      - "${SSL_VISION_MULTICAST_ADDR}:${SSL_VISION_VIZ_PORT}"
      - "-address"
      - ":${WEB_VISION_UI_PORT}"
    ports:
      - "${WEB_VISION_UI_PORT}:${WEB_VISION_UI_PORT}"
    networks:
      - simulation
    depends_on:
      - viewer
