# docker-compose.local-gameviewer.yml (GHCR controller, local game viewer)
services:
  game-viewer:
    build: ./GameViewer
    image: ""
    tty: true
    environment:
      - SSL_VISION_MULTICAST_ADDR=${SSL_VISION_MULTICAST_ADDR}
      - SSL_VISION_MULTICAST_PORT=${SSL_SIM_VISION_MAIN_PORT}
    network_mode: "host"
    container_name: viewer
    depends_on:
      - controller
    volumes:
      - ./GameViewer/:/var/GameViewer
      - ./.env:/var/GameViewer/.env
    command: tail -f /dev/null
