services:
  sim:
    image: ghcr.io/liu-seegoals/ssl-vision:latest
    # container_name: ssl_vision_container
    environment:
      - QT_QPA_PLATFORM=offscreen
    restart: no
    stdin_open: true
    container_name: vision
    tty: true
    networks:
      - simulation

  ssl-vision-client:
    image: robocupssl/ssl-vision-client:latest
    command:
      - "-visionAddress"
      - "${SSL_VISION_MULTICAST_ADDR}:${SSL_REAL_VISION_MAIN_PORT}"
      - "-visualizationAddress"
      - "${SSL_VISION_MULTICAST_ADDR}:${SSL_VISION_VIZ_PORT}"
      - "-address"
      - ":${WEB_VISION_UI_PORT}"
    ports:
      - "${WEB_VISION_UI_PORT}:${WEB_VISION_UI_PORT}"
    container_name: ssl-viewer
    networks:
      - simulation
    depends_on:
      - sim
