# docker-compose.local-controller.yml (local controller, GHCR game viewer)
services:
  controller:
    build: ./controller
    image: ""
    tty: true
    container_name: ai
    network_mode: "host"
    volumes:
      - ./controller/:/var/controller
      - ./.env:/.env # If this was /var/controller/.env then the .env file will be volumed into the workspace of GameViewer
    command: tail -f /dev/null
