services:

  ssl-vision-client:
    image: robocupssl/ssl-vision-client:latest
    command:
      - "-visionAddress"
      - "${SSL_VISION_MULTICAST_ADDR}:${SSL_SIM_VISION_MAIN_PORT}"
      - "-visualizationAddress"
      - "${SSL_VISION_MULTICAST_ADDR}:${SSL_VISION_VIZ_PORT}"
      - "-address"
      - ":${WEB_VISION_UI_PORT}"
    ports:
      - "${WEB_VISION_UI_PORT}:${WEB_VISION_UI_PORT}"
    networks:
      - simulation
    restart: "no"
    container_name: ssl-viewer
    depends_on:
      - sim
  
  ssl-game-controller:
    image: robocupssl/ssl-game-controller:latest
    command:
      - "-visionAddress"
      - "${SSL_VISION_MULTICAST_ADDR}:${SSL_SIM_VISION_MAIN_PORT}"
      - "-trackerAddress"
      - "${SSL_VISION_MULTICAST_ADDR}:${SSL_SIM_VISION_MAIN_PORT}"
      - "-publishAddress"
      - "${GC_PUBLISH_ADDR}:${GC_PUBLISH_PORT}"
      - "-address"
      - ":${WEB_GC_UI_PORT}"
    ports:
      - "${WEB_GC_UI_PORT}:${WEB_GC_UI_PORT}"
    networks:
      - simulation
    container_name: game-controller
    depends_on:
      - sim
    restart: "no"
    volumes:
      - ./config/:/config
      - ./data/:/data

  sim:
    image: roboticserlangen/simulatorcli:commit-6a4e1c06533b
    environment:
      GEOMETRY: "2020B"
      REALISM: "RC2021"
    networks:
      - simulation
    restart: "no"
    container_name: vision

  controller:
    image: ghcr.io/liu-seegoals/controller:latest
    env_file:
      - .env
    tty: true
    ports:
      - "8080:8080"
    networks:
      - simulation
    container_name: ai
    restart: "no"
    volumes:
      - ./.env:/var/controller/.env

  game-viewer:
    image: ghcr.io/liu-seegoals/game-viewer:latest
    tty: true
    ports:
      - "5173:5173"
      - "3000:3000"
    networks:
      - simulation
    depends_on:
      - controller
    container_name: viewer
    restart: "no"
    volumes:
      - ./.env:/.env

networks:
  simulation:
    driver: bridge
