# docker-compose.local-gameviewer.yml (GHCR controller, local game viewer)
services:
  game-viewer:
    build: ./GameViewer
    image: ""
    tty: true
    environment:
      - SSL_VISION_MULTICAST_ADDR=${SSL_VISION_MULTICAST_ADDR}
      - SSL_VISION_MULTICAST_PORT=${SSL_SIM_VISION_MAIN_PORT}
    ports:
      - "5173:5173"
      - "3000:3000" # Honest to God I have no idea why this is required. But without it the backend server listening to multicast cannot talk to the webpage
    networks:
      - simulation
    container_name: viewer
    depends_on:
      - controller
    volumes:
      - ./GameViewer/:/var/GameViewer
      - ./.env:/var/GameViewer/.env
    command: tail -f /dev/null
