services:
  ai:
    image: ghcr.io/liu-seegoals/controller:latest
    container_name: ${DOCKER_NAME_AI}
    restart: "no"
    volumes:
      - ../environment.ini:/var/controller/.env

  game-viewer:
    image: ghcr.io/liu-seegoals/game-viewer:latest
    container_name: ${DOCKER_NAME_GAME_VIEWER}
    depends_on:
      - ${DOCKER_NAME_AI}
    environment:
      - SSL_VISION_MULTICAST_ADDR=${SSL_VISION_MULTICAST_ADDR}
      - SSL_VISION_MULTICAST_PORT=${SSL_VISION_SIM_MAIN_PORT}
    restart: "no"
    env_file: ../environment.ini
    volumes:
      - ../environment.ini:/var/GameViewer/.env

  ssl-vision-client:
    image: robocupssl/ssl-vision-client:latest
    container_name: ${DOCKER_NAME_SSL_VISION_CLIENT}
    command:
      - "-visionAddress"
      - "${SSL_VISION_MULTICAST_ADDR}:${SSL_VISION_SIM_MAIN_PORT}"
      - "-visualizationAddress"
      - "${SSL_VISION_MULTICAST_ADDR}:${SSL_VISION_VIZ_PORT}"
      - "-address"
      - ":${SSL_VISION_CLIENT_PORT}"
    restart: "no"

  ssl-game-controller:
    image: robocupssl/ssl-game-controller:latest
    container_name: ${DOCKER_NAME_SSL_GAME_CONTROLLER}
    command:
      - "-visionAddress"
      - "${SSL_VISION_MULTICAST_ADDR}:${SSL_VISION_SIM_MAIN_PORT}"
      - "-trackerAddress"
      - "${SSL_VISION_MULTICAST_ADDR}:${SSL_VISION_SIM_MAIN_PORT}"
      - "-publishAddress"
      - "${SSL_GAME_CONTROLLER_PUBLISH_ADDR}:${SSL_GAME_CONTROLLER_PUBLISH_PORT}"
      - "-address"
      - ":${SSL_GAME_CONTROLLER_UI_PORT}"
    restart: "no"
    volumes:
      - ../software/GameController/config/:/config
      - ../software/GameController/data/:/data

  er-sim:
    image: roboticserlangen/simulatorcli:commit-6a4e1c06533b
    container_name: ${DOCKER_NAME_ER_SIM}
    environment:
      GEOMETRY: ${SIM_GEOMETRY}
      REALISM: ${SIM_REALISM}
    restart: "no"

  gr-sim:
    image: robocupssl/grsim:latest
    container_name: ${DOCKER_NAME_GR_SIM}
    environment:
      - VNC_PASSWORD=vnc
      - VNC_GEOMETRY=1920x1080
    restart: "no"
