services:
  ssl-vision:
    image: ghcr.io/liu-seegoals/ssl-vision:latest
    container_name: ${DOCKER_NAME_SSL_VISION}
    environment:
      - QT_QPA_PLATFORM=offscreen
    restart: no
    stdin_open: true
    network_mode: "host"
    tty: true

  game-viewer:
    environment:
      - SSL_VISION_MULTICAST_ADDR=${SSL_VISION_MULTICAST_ADDR}
      - SSL_VISION_MULTICAST_PORT=${SSL_VISION_REAL_MAIN_PORT}
    depends_on:
      - ${DOCKER_NAME_AI}
