services:
  ssl-vision-client:
    image: robocupssl/ssl-vision-client:latest
    container_name: ${DOCKER_NAME_SSL_VIEWER}
    command:
      - "-visionAddress"
      - "${SSL_VISION_MULTICAST_ADDR}:${SSL_SIM_VISION_MAIN_PORT}"
      - "-visualizationAddress"
      - "${SSL_VISION_MULTICAST_ADDR}:${SSL_VISION_VIZ_PORT}"
      - "-address"
      - ":${WEB_VISION_UI_PORT}"
    restart: "no"
    network_mode: "host"

  ssl-game-controller:
    image: robocupssl/ssl-game-controller:latest
    container_name: ${DOCKER_NAME_GAME_CONTROLLER}
    command:
      - "-visionAddress"
      - "${SSL_VISION_MULTICAST_ADDR}:${SSL_SIM_VISION_MAIN_PORT}"
      - "-trackerAddress"
      - "${SSL_VISION_MULTICAST_ADDR}:${SSL_SIM_VISION_MAIN_PORT}"
      - "-publishAddress"
      - "${GC_PUBLISH_ADDR}:${GC_PUBLISH_PORT}"
      - "-address"
      - ":${WEB_GC_UI_PORT}"
    restart: "no"
    volumes:
      - ../software/config/:/config
      - ../software/data/:/data
    network_mode: "host"

  sim:
    image: roboticserlangen/simulatorcli:commit-6a4e1c06533b
    container_name: ${DOCKER_NAME_VISION}
    environment:
      GEOMETRY: "2020"
      REALISM: "RC2021"
    restart: "no"
    network_mode: "host"

  controller:
    image: ghcr.io/liu-seegoals/controller:latest
    container_name: ${DOCKER_NAME_AI}
    tty: true
    restart: "no"
    volumes:
      - ../environment.ini:/var/controller/.env
    network_mode: "host"

  game-viewer:
    image: ghcr.io/liu-seegoals/game-viewer:latest
    container_name: ${DOCKER_NAME_VIEWER}
    tty: true
    environment:
      - SSL_VISION_MULTICAST_ADDR=${SSL_VISION_MULTICAST_ADDR}
      - SSL_VISION_MULTICAST_PORT=${SSL_SIM_VISION_MAIN_PORT}
    network_mode: "host"
    depends_on:
      - controller
    restart: "no"
    volumes:
      - ../environment.ini:/.env
