services:
  ai:
    network_mode: "host"

  game-viewer:
    network_mode: "host"

  ssl-game-controller:
    profiles:
      - donotstart

  er-sim:
    profiles:
      - donotstart

  vision:
    profiles:
      - donotstart
