services:
  ai:
    image: ""
    build: ../software/controller
    volumes:
      - ../environment.ini:/var/controller/.env
      - ../software/controller/:/var/controller
    working_dir: /var/controller/cmd
    tty: true
    command: tail -f /dev/null