services:
  ai:
    networks:
      - simulation-network

  game-viewer:
    ports:
      - "${GAME_VIEWER_PORT}:${GAME_VIEWER_PORT}"
    networks:
      - simulation-network

  ssl-vision-client:
    ports:
      - "${SSL_VISION_CLIENT_PORT}:${SSL_VISION_CLIENT_PORT}"
    networks:
      - simulation-network

  ssl-game-controller:
    ports:
      - "${SSL_GAME_CONTROLLER_UI_PORT}:${SSL_GAME_CONTROLLER_UI_PORT}"
    networks:
      - simulation-network

  er-sim:
    networks:
      - simulation-network

networks:
  simulation-network:
    driver: bridge
